# Generated by Django 2.2 on 2019-07-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190715_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostManager',
        ),
    ]
